version: '3'
 
services:
  blog-front:   
    container_name: blog-front
    image: node:10
    working_dir: /app
    ports:
      - "8030:3000"
    volumes:
      - ./:/app
    environment:
      CHOKIDAR_USEPOLLING: 1  
      SERVER_HOST: http://localhost:8030
    command:
      - /bin/bash
      - -c
      - | 
        npm install
        npm start